services:
  wa-baileys-service:
    build: .
    container_name: bailey_container
    ports:
      - "3001:3001"
    volumes:
      - ./auth_info_baileys:/app/auth_info_baileys
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
